version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: file-intake-db-veleiro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3309:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      args:
        DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}"
        PULSE_API_KEY: ${PULSE_API_KEY}
    container_name: file-intake-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PULSE_API_KEY: ${PULSE_API_KEY}
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}"

volumes:
  mysql-data: